/**************************************************************************
File:               dsys0tgt.h
Author:             ISaGRAF Inc.
Creation date:      01/02/2012 - 11:21
***************************************************************************/
#ifndef _DSYS0TGT_H /* nested Headers management */
#define _DSYS0TGT_H

/* WARNING!
This file is generated by TDBuild, do not modify the content of this file
manually.
*/

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    TARGET_NAME
* \n\b Usage:   Name of the target.
*/
/******************************************************************************/
#define TARGET_NAME "ACE-TARGET_L"

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_TMM_L
* \n\b Usage:   Enables the large memory model target.
*/
/******************************************************************************/
#define ISA_TMM_L

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    INTEL
* \n\b Usage:   Enables Intel byte order (Little Endian).
*/
/******************************************************************************/
#define INTEL

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_SCC
* \n\b Usage:   'C' code resource feature vs TIC code
*/
/******************************************************************************/
#undef ITGTDEF_SCC

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ALIGN
* \n\b Usage:   Definition of the maximum alignement value
*/
/******************************************************************************/
#define ISA_ALIGN 4

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_CR
* \n\b Usage:   Carriage return for traces.
*/
/******************************************************************************/
#define ISA_CR "\n"

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_RESNAME
* \n\b Usage:   Definition of system variable: RESNAME.
*/
/******************************************************************************/
#define ISA_SYSVA_RESNAME 0X4

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_CYCLEDATE
* \n\b Usage:   Definition of system variable: CYCLEDATE.
*/
/******************************************************************************/
#define ISA_SYSVA_CYCLEDATE 0X108

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_TCYCYCTIME
* \n\b Usage:   Definition of system variable: TCYCYCTIME.
*/
/******************************************************************************/
#define ISA_SYSVA_TCYCYCTIME 0X10C

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_TCYCURRENT
* \n\b Usage:   Definition of system variable: TCYCURRENT.
*/
/******************************************************************************/
#define ISA_SYSVA_TCYCURRENT 0X110

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_TCYMAXIMUM
* \n\b Usage:   Definition of system variable: TCYMAXIMUM.
*/
/******************************************************************************/
#define ISA_SYSVA_TCYMAXIMUM 0X114

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_TCYOVERFLOW
* \n\b Usage:   Definition of system variable: TCYOVERFLOW.
*/
/******************************************************************************/
#define ISA_SYSVA_TCYOVERFLOW 0X118

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_SCANCNT
* \n\b Usage:   Definition of system variable: SCANCNT.
*/
/******************************************************************************/
#define ISA_SYSVA_SCANCNT 0X11C

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_CYCLECNT
* \n\b Usage:   Definition of system variable: CYCLECNT.
*/
/******************************************************************************/
#define ISA_SYSVA_CYCLECNT 0X120

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_RESMODE
* \n\b Usage:   Definition of system variable: RESMODE.
*/
/******************************************************************************/
#define ISA_SYSVA_RESMODE 0X124

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_CCEXEC
* \n\b Usage:   Definition of system variable: CCEXEC.
*/
/******************************************************************************/
#define ISA_SYSVA_CCEXEC 0X125

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_KVBPERR
* \n\b Usage:   Definition of system variable: KVPERR.
*/
/******************************************************************************/
#define ISA_SYSVA_KVBPERR 0X126

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_KVBCERR
* \n\b Usage:   Definition of system variable: KVBCERR.
*/
/******************************************************************************/
#define ISA_SYSVA_KVBCERR 0X127

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_WNGNUM
* \n\b Usage:   Definition of system variable: WNGNUM.
*/
/******************************************************************************/
#define ISA_SYSVA_WNGNUM 0X128

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_WNGARG
* \n\b Usage:   Definition of system variable: WNGARG.
*/
/******************************************************************************/
#define ISA_SYSVA_WNGARG 0X12C

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_WNGCMPTNM
* \n\b Usage:   Definition of system variable: WNGCMPTNM.
*/
/******************************************************************************/
#define ISA_SYSVA_WNGCMPTNM 0X130

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_WNGCMD
* \n\b Usage:   Definition of system variable: WNGCMD.
*/
/******************************************************************************/
#define ISA_SYSVA_WNGCMD 0X13B

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_ZZZZ
* \n\b Usage:   Definition of system variable: ZZZZ
*/
/******************************************************************************/
#define ISA_SYSVA_ZZZZ 0

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_BFDATASZE
* \n\b Usage:   Definition of system variable: BFDATASZE
*/
/******************************************************************************/
#define ISA_SYSVA_BFDATASZE 0X160

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_KPVRDTBPTRS
* \n\b Usage:   Definition of system variable: KPVRDTBPRS
*/
/******************************************************************************/
#define ISA_SYSVA_KPVRDTBPTRS 0X164

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_SLAVENUM
* \n\b Usage:   Definition of system variable: SLAVENUM
*/
/******************************************************************************/
#define ISA_SYSVA_SLAVENUM 0X168

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_CYCTIMEBASE
* \n\b Usage:   Definition of system variable: CYCTIMEBASE
*/
/******************************************************************************/
#define ISA_SYSVA_CYCTIMEBASE 0X16C

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_MICROCYCLEDATE
* \n\b Usage:   Definition of system variable: MICROCYCLEDATE
*/
/******************************************************************************/
#define ISA_SYSVA_MICROCYCLEDATE 0X170

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_MICROTCYCYCTIME
* \n\b Usage:   Definition of system variable: MICROTCYCYCTIME
*/
/******************************************************************************/
#define ISA_SYSVA_MICROTCYCYCTIME 0X174

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_MICROTCYCURRENT
* \n\b Usage:   Definition of system variable: MICROTCYCURRENT
*/
/******************************************************************************/
#define ISA_SYSVA_MICROTCYCURRENT 0X178

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_MICROTCYMAXIMUM
* \n\b Usage:   Definition of system variable: MICROTCYMAXIMUM
*/
/******************************************************************************/
#define ISA_SYSVA_MICROTCYMAXIMUM 0X17C

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_SYSVA_LASTSYSVALIM
* \n\b Usage:   Definition of system variable: LASTSYSVALIM.
*/
/******************************************************************************/
#define ISA_SYSVA_LASTSYSVALIM 0X400

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_FCALL_MAXPARAM
* \n\b Usage:   Functions call parameter passing: Max nbr of parameters.
*/
/******************************************************************************/
#define ISA_FCALL_MAXPARAM 128

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_DOUBLE
* \n\b Usage:   Target supports data type: LREAL.
*/
/******************************************************************************/
#define ITGTDEF_DOUBLE

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_FLOAT
* \n\b Usage:   Target supports data type: REAL.
*/
/******************************************************************************/
#define ITGTDEF_FLOAT

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_STRING
* \n\b Usage:   Target supports data type: STRING.
*/
/******************************************************************************/
#define ITGTDEF_STRING

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_BOOL
* \n\b Usage:   Target supports data type: BOOL.
*/
/******************************************************************************/
#define ITGTDEF_BOOL

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_DATE
* \n\b Usage:   Target supports data type: DATE.
*/
/******************************************************************************/
#define ITGTDEF_DATE

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_INT32
* \n\b Usage:   Target supports data type: DINT.
*/
/******************************************************************************/
#define ITGTDEF_INT32

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_INT16
* \n\b Usage:   Target supports data type: INT.
*/
/******************************************************************************/
#define ITGTDEF_INT16

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_INT64
* \n\b Usage:   Target supports data type: LINT.
*/
/******************************************************************************/
#define ITGTDEF_INT64

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_INT8
* \n\b Usage:   Target supports data type: SINT.
*/
/******************************************************************************/
#define ITGTDEF_INT8

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_TIME
* \n\b Usage:   Target supports data type: TIME.
*/
/******************************************************************************/
#define ITGTDEF_TIME

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_UINT32
* \n\b Usage:   Target supports data type: UDINT.
*/
/******************************************************************************/
#define ITGTDEF_UINT32

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_UINT16
* \n\b Usage:   Target supports data type: UINT.
*/
/******************************************************************************/
#define ITGTDEF_UINT16

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_UINT64
* \n\b Usage:   Target supports data type: ULINT.
*/
/******************************************************************************/
#define ITGTDEF_UINT64

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_UINT8
* \n\b Usage:   Target supports data type: USINT.
*/
/******************************************************************************/
#define ITGTDEF_UINT8

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_KVB
* \n\b Usage:   Enables kernel variable binding.
*/
/******************************************************************************/
#define ITGTDEF_KVB

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_MODIF
* \n\b Usage:   Enables On-line modification feature (without stopping resource).
*/
/******************************************************************************/
#define ITGTDEF_MODIF

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_RETAIN
* \n\b Usage:   Enables Retain variables.
*/
/******************************************************************************/
#define ITGTDEF_RETAIN

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_CONF_PASSWORD
* \n\b Usage:   Enable the IXL password management for the Config.
*/
/******************************************************************************/
#define ITGTDEF_CONF_PASSWORD

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_OPTIMIZED_TIC
* \n\b Usage:   Enables execution of new optimized TIC.
*/
/******************************************************************************/
#define ITGTDEF_OPTIMIZED_TIC

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_MONOTASK
* \n\b Usage:   Enables monotask implementation.
*/
/******************************************************************************/
#undef ITGTDEF_MONOTASK

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_MICRO_CYC_TIME
* \n\b Usage:   Enables Microsecond Cycle Time.
*/
/******************************************************************************/
#undef ITGTDEF_MICRO_CYC_TIME

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_ABS
* \n\b Usage:   Target supports standard function: ABS.
*/
/******************************************************************************/
#define ITGTDEF_ABS

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_COS
* \n\b Usage:   Target supports standard function: COS.
*/
/******************************************************************************/
#define ITGTDEF_COS

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_ACOS
* \n\b Usage:   Target supports standard function: ACOS.
*/
/******************************************************************************/
#define ITGTDEF_ACOS

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_SIN
* \n\b Usage:   Target supports standard function: SIN.
*/
/******************************************************************************/
#define ITGTDEF_SIN

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_ASIN
* \n\b Usage:   Target supports standard function: ASIN.
*/
/******************************************************************************/
#define ITGTDEF_ASIN

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_TAN
* \n\b Usage:   Target supports standard function: TAN.
*/
/******************************************************************************/
#define ITGTDEF_TAN

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_ATAN
* \n\b Usage:   Target supports standard function: ATAN.
*/
/******************************************************************************/
#define ITGTDEF_ATAN

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_EXPT
* \n\b Usage:   Target supports standard function: EXPT.
*/
/******************************************************************************/
#define ITGTDEF_EXPT

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_POW
* \n\b Usage:   Target supports standard function: POW.
*/
/******************************************************************************/
#define ITGTDEF_POW

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_LOG
* \n\b Usage:   Target supports standard function: LOG.
*/
/******************************************************************************/
#define ITGTDEF_LOG

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_SQRT
* \n\b Usage:   Target supports standard function: SQRT.
*/
/******************************************************************************/
#define ITGTDEF_SQRT

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_MOD
* \n\b Usage:   Target supports standard function: MOD.
*/
/******************************************************************************/
#define ITGTDEF_MOD

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_TRUNC
* \n\b Usage:   Target supports standard function: TRUNC.
*/
/******************************************************************************/
#define ITGTDEF_TRUNC

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_RAND
* \n\b Usage:   Target supports standard function: RAND.
*/
/******************************************************************************/
#define ITGTDEF_RAND

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_ODD
* \n\b Usage:   Target supports standard function: ODD.
*/
/******************************************************************************/
#define ITGTDEF_ODD

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_MIN
* \n\b Usage:   Target supports standard function: MIN.
*/
/******************************************************************************/
#define ITGTDEF_MIN

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_MAX
* \n\b Usage:   Target supports standard function: MAX.
*/
/******************************************************************************/
#define ITGTDEF_MAX

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_LIMIT
* \n\b Usage:   Target supports standard function: LIMIT.
*/
/******************************************************************************/
#define ITGTDEF_LIMIT

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_SEL
* \n\b Usage:   Target supports standard function: SEL.
*/
/******************************************************************************/
#define ITGTDEF_SEL

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_MUX4
* \n\b Usage:   Target supports standard function: MUX4.
*/
/******************************************************************************/
#define ITGTDEF_MUX4

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_MUX8
* \n\b Usage:   Target supports standard function: MUX8.
*/
/******************************************************************************/
#define ITGTDEF_MUX8

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_SHL
* \n\b Usage:   Target supports standard function: SHL.
*/
/******************************************************************************/
#define ITGTDEF_SHL

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_SHR
* \n\b Usage:   Target supports standard function: SHR.
*/
/******************************************************************************/
#define ITGTDEF_SHR

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_ROL
* \n\b Usage:   Target supports standard function: ROL.
*/
/******************************************************************************/
#define ITGTDEF_ROL

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_ROR
* \n\b Usage:   Target supports standard function: ROR.
*/
/******************************************************************************/
#define ITGTDEF_ROR

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_CURRENT_ISA_DATE
* \n\b Usage:   Target supports standard function: CURRENT_ISA_DATE.
*/
/******************************************************************************/
#define ITGTDEF_CURRENT_ISA_DATE

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_SUBDATEDATE
* \n\b Usage:   Target supports standard function: SUBDATEDATE.
*/
/******************************************************************************/
#define ITGTDEF_SUBDATEDATE

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_LIM_ALRM
* \n\b Usage:   Target supports standard function block: LIM_ALRM.
*/
/******************************************************************************/
#define ITGTDEF_LIM_ALRM

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_SR
* \n\b Usage:   Target supports standard function block: SR.
*/
/******************************************************************************/
#define ITGTDEF_SR

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_RS
* \n\b Usage:   Target supports standard function block: RS.
*/
/******************************************************************************/
#define ITGTDEF_RS

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_RTRIG
* \n\b Usage:   Target supports standard function block: RTRIG.
*/
/******************************************************************************/
#define ITGTDEF_RTRIG

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_FTRIG
* \n\b Usage:   Target supports standard function block: FTRIG.
*/
/******************************************************************************/
#define ITGTDEF_FTRIG

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_CTD
* \n\b Usage:   Target supports standard function block: CTD.
*/
/******************************************************************************/
#define ITGTDEF_CTD

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_CTU
* \n\b Usage:   Target supports standard function block: CTU.
*/
/******************************************************************************/
#define ITGTDEF_CTU

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_CTUD
* \n\b Usage:   Target supports standard function block: CTUD.
*/
/******************************************************************************/
#define ITGTDEF_CTUD

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_CMP
* \n\b Usage:   Target supports standard function block: CMP.
*/
/******************************************************************************/
#define ITGTDEF_CMP

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_AVERAGE
* \n\b Usage:   Target supports standard function block: AVERAGE.
*/
/******************************************************************************/
#define ITGTDEF_AVERAGE

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_CFB
* \n\b Usage:   Target supports standard function block: CONNECT, URCV_S, USEND.
*/
/******************************************************************************/
#define ITGTDEF_CFB

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_BLINK
* \n\b Usage:   Target supports standard function block: BLINK
*/
/******************************************************************************/
#define ITGTDEF_BLINK

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_SIG_GEN
* \n\b Usage:   Target supports standard function block: SIG_GEN.
*/
/******************************************************************************/
#define ITGTDEF_SIG_GEN

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_DERIVATE
* \n\b Usage:   Target supports standard function block: DERIVATE.
*/
/******************************************************************************/
#define ITGTDEF_DERIVATE

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_INTEGRAL
* \n\b Usage:   Target supports standard function block: INTEGRAL.
*/
/******************************************************************************/
#define ITGTDEF_INTEGRAL

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_HYSTER
* \n\b Usage:   Target supports standard function block: HYSTER.
*/
/******************************************************************************/
#define ITGTDEF_HYSTER

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_STACKINT
* \n\b Usage:   Target supports standard function block: STACKINT.
*/
/******************************************************************************/
#define ITGTDEF_STACKINT

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_SEMA
* \n\b Usage:   Target supports standard function block: SEMA.
*/
/******************************************************************************/
#define ITGTDEF_SEMA

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_TON
* \n\b Usage:   Target supports standard function block: TON.
*/
/******************************************************************************/
#define ITGTDEF_TON

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_TOF
* \n\b Usage:   Target supports standard function block: TOF.
*/
/******************************************************************************/
#define ITGTDEF_TOF

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_TP
* \n\b Usage:   Target supports standard function block: TP.
*/
/******************************************************************************/
#define ITGTDEF_TP

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_NEW_ARRAY_AND_FB
* \n\b Usage:   Target supports flexible arrays and function block parameter passing by reference.
*/
/******************************************************************************/
#define ITGTDEF_NEW_ARRAY_AND_FB

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_INTERRUPT
* \n\b Usage:   Target supports user interrupts
*/
/******************************************************************************/
#define ITGTDEF_INTERRUPT

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_MAXCALLSTACKDEPTH
* \n\b Usage:   Maximum allowed call stack depth.
*/
/******************************************************************************/
#define ISA_MAXCALLSTACKDEPTH 0

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_BIGPOUS
* \n\b Usage:   Target supports POUs larger than 64k
*/
/******************************************************************************/
#define ITGTDEF_BIGPOUS

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_ASCII
* \n\b Usage:   Target supports standard function: ASCII
*/
/******************************************************************************/
#define ITGTDEF_ASCII

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_CHAR
* \n\b Usage:   Target supports standard function: CHAR
*/
/******************************************************************************/
#define ITGTDEF_CHAR

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_DELETE
* \n\b Usage:   Target supports standard function: DELETE
*/
/******************************************************************************/
#define ITGTDEF_DELETE

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_FIND
* \n\b Usage:   Target supports standard function: FIND
*/
/******************************************************************************/
#define ITGTDEF_FIND

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_INSERT
* \n\b Usage:   Target supports standard function: INSERT
*/
/******************************************************************************/
#define ITGTDEF_INSERT

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_LEFT
* \n\b Usage:   Target supports standard function: LEFT
*/
/******************************************************************************/
#define ITGTDEF_LEFT

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_MID
* \n\b Usage:   Target supports standard function: MID
*/
/******************************************************************************/
#define ITGTDEF_MID

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_MLEN
* \n\b Usage:   Target supports standard function: MLEN
*/
/******************************************************************************/
#define ITGTDEF_MLEN

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_REPLACE
* \n\b Usage:   Target supports standard function: REPLACE
*/
/******************************************************************************/
#define ITGTDEF_REPLACE

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_RIGHT
* \n\b Usage:   Target supports standard function: RIGHT
*/
/******************************************************************************/
#define ITGTDEF_RIGHT

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_AND_MASK
* \n\b Usage:   Target supports standard function: AND_MASK
*/
/******************************************************************************/
#define ITGTDEF_AND_MASK

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_OR_MASK
* \n\b Usage:   Target supports standard function: OR_MASK
*/
/******************************************************************************/
#define ITGTDEF_OR_MASK

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_NOT_MASK
* \n\b Usage:   Target supports standard function: NOT_MASK
*/
/******************************************************************************/
#define ITGTDEF_NOT_MASK

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_XOR_MASK
* \n\b Usage:   Target supports standard function: XOR_MASK
*/
/******************************************************************************/
#define ITGTDEF_XOR_MASK

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ISA_RESNBR
* \n\b Usage:   Maximum number of resources per device
*/
/******************************************************************************/
#define ISA_RESNBR 8

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_ENH_ONLINE_CHANGE
* \n\b Usage:   Definition for Enhance Online Change (only for Enhanced Target)
*/
/******************************************************************************/
#define ITGTDEF_ENH_ONLINE_CHANGE

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_SFC_TRANS_PRIORITY
* \n\b Usage:   Target supports SFC transition priorities
*/
/******************************************************************************/
#define ITGTDEF_SFC_TRANS_PRIORITY

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_WIRING_MEM_OF_CPX
* \n\b Usage:   Target supports wiring complex sub-variables to I/O channels
*/
/******************************************************************************/
#define ITGTDEF_WIRING_MEM_OF_CPX

/******************** DOXYGEN COMPILE-TIME CONDITIONAL *************************/
/*! \addtogroup   CompileConditional Compile-time Conditionals
* \addtogroup     TargetFeatures Target Features
* \ingroup        CompileConditional
*******************************************************************************
* \n\b Name:    ITGTDEF_FAILOVER
* \n\b Usage:   Enables Failover Manager task.
*/
/******************************************************************************/
#undef ITGTDEF_FAILOVER

/**************************************************************************
Extended Parameters Structure
**************************************************************************/

#endif /* _DSYS0TGT_H */

/* eof ********************************************************************/

